// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsc2BJk5H6zW-h_snyMOv7IYTVCBowcDA',
    appId: '1:792895590056:web:960a36866938a07817fc9d',
    messagingSenderId: '792895590056',
    projectId: 'coastercenterreport',
    authDomain: 'coastercenterreport.firebaseapp.com',
    storageBucket: 'coastercenterreport.firebasestorage.app',
    measurementId: 'G-N6ZW0VXC7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGNLK494aYv0J9-efnZaojW1awpVA9EA',
    appId: '1:792895590056:android:28cc8e67993a6c1d17fc9d',
    messagingSenderId: '792895590056',
    projectId: 'coastercenterreport',
    storageBucket: 'coastercenterreport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQ96zPcz8K9PuOWdBF2stLPzBi_4Vt0M',
    appId: '1:792895590056:ios:cc2d925ef1526f8517fc9d',
    messagingSenderId: '792895590056',
    projectId: 'coastercenterreport',
    storageBucket: 'coastercenterreport.firebasestorage.app',
    iosBundleId: 'com.example.coastercenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQ96zPcz8K9PuOWdBF2stLPzBi_4Vt0M',
    appId: '1:792895590056:ios:cc2d925ef1526f8517fc9d',
    messagingSenderId: '792895590056',
    projectId: 'coastercenterreport',
    storageBucket: 'coastercenterreport.firebasestorage.app',
    iosBundleId: 'com.example.coastercenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsc2BJk5H6zW-h_snyMOv7IYTVCBowcDA',
    appId: '1:792895590056:web:5ea91ac181e3d97417fc9d',
    messagingSenderId: '792895590056',
    projectId: 'coastercenterreport',
    authDomain: 'coastercenterreport.firebaseapp.com',
    storageBucket: 'coastercenterreport.firebasestorage.app',
    measurementId: 'G-1NB2RG89FZ',
  );
}
